### ISSUE TITLE
Replace Unity with Autofac?

### ISSUE THREAD

**Issue by AjaySewradj** [darrencauthon/AutoMoq#37]
Is it possible to swap out Unity and replace it with Autofac, or any other IoC framework?

**Comment by darrencauthon** [comment]
@AjaySewradj I'm very sorry for the late reply!

I have tried this before.... I have (or had?) a branch where I created an abstraction, with the intention that it would allow me to swap out Unity for anything that could provide the same behavior.  It seems feasible, but I don't think I felt good about the abstraction so I thought I'd give it a second shot later.

And I have done this before; I helped with some IoC code for the old MVC Turbine project, so I had a lot of practice making multiple IoC containers conform to the same contract.  So I think it is definitely possible, but...

The thing I can't really explain, even to myself is:  Why would someone want to swap the IoC container?  The only reason I can think of is that it might interfere with someone who uses a different version of Unity.  But that was resolved when someone contributed the update for the 2.0 release, which uses the latest Unity.

One reason I think Unity is a good fit is that it doesn't seem to be as popular as the "hip" IoC containers... like AutoFac.  So AutoMoq is safe because it is less likely to conflict with the application's IoC version.  Plus, Unity has been pretty stable in my experience, versus the other IoC containers where developers are still tinkering on the same basic ideas.

**Comment by AjaySewradj** [comment]
@darrencauthon Thanks for the reply!

The reason for my question was based on the following scenario:

I was interested in using the Automoq library, but not interested in adding a dependency to Unity (or another IoC container), since my project already has a hard dependency on Autofac.
It would be nice if the features of Automoq could be used in combination with our current infrastructure.

I eventually opted for another library, Autofac.Extras.Moq, which offers similar functionality as Automoq.

**Comment by darrencauthon** [comment]
@AjaySewradj That's cool.  I understand what you mean about the dependency.  I've gone ahead with the Unity dependency in my solutions, but only in the test projects.  So, it's not like Unity spreads out into production code. :smile: And for most AutoMoq users, Unity is never touched, so.... if I were every able to implement its behaviors without using Unity, I could drop Unity and nobody would notice.

I only have Unity in here because, many years ago, it provided the simplest solution for injection custom behavior into the resolution process. :smile:

I'm going to close your ticket for now, if you don't mind.  Not that I'm against it, but because I don't think it will be implemented any time soon... and it is not a task I'd want anybody else to take on.  Our top priority right now is getting .Net Core compatibility.  Perhaps after that, we could take this idea up.
